import { Inter } from "next/font/google";
import "./globals.css";
import Context from "./(context)/globalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Take my Card, please!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Context>
        <body className={inter.className}>{children}</body>
      </Context>
    </html>
  );
}
